name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r starter/requirements.txt
        pip install flake8 pytest
    - name: Run flake8
      run: |
        cd starter
        flake8 .
    - name: Start FastAPI application
      run: |
        cd starter
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Give the server some time to start
    - name: Run tests
      run: |
        cd starter
        pytest test_model_and_api.py -v
    - name: Check test count
      run: |
        test_count=$(pytest starter/test_model_and_api.py --collect-only -q | tail -n 1 | cut -d: -f2)
        if [ "$test_count" -lt 6 ]; then
          echo "Error: There are fewer than 6 tests."
          exit 1
        fi
